
services:
  db:
    image: postgres:13
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: banksystem
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
